import WrapperLayout from './WrapperLayout';
import './globals.css';

const metadata = {
  title: 'GreenShop',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa-IR" dir="rtl">
      <body>
        <WrapperLayout>{children}</WrapperLayout>
      </body>
    </html>
  );
}
